version: '3.8'

services:
  detect-executor:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=prod
      - DETECT_SERVER_PORT=8080
      - DETECT_LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis服务（后续步骤会用到）
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # MySQL服务（后续步骤会用到）
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=detect_executor
      - MYSQL_USER=detect
      - MYSQL_PASSWORD=detect123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  redis_data:
  mysql_data:
