server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

database:
  host: "${DETECT_DB_HOST:localhost}"
  port: ${DETECT_DB_PORT:3306}
  username: "${DETECT_DB_USER:root}"
  password: "${DETECT_DB_PASSWORD:password}"
  database: "${DETECT_DB_NAME:detect_db_dev}"
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: "1h"

redis:
  host: "${DETECT_REDIS_HOST:localhost}"
  port: ${DETECT_REDIS_PORT:6379}
  password: "${DETECT_REDIS_PASSWORD:}"
  db: ${DETECT_REDIS_DB:0}
  pool_size: ${DETECT_REDIS_POOL_SIZE:10}
  min_idle_conns: ${DETECT_REDIS_MIN_IDLE_CONNS:5}
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

detect:
  max_workers: 100
  batch_size: 10
  queue_size: 1000
  timeout: "30s"
  retry_count: 3
  retry_delay: "1s"
  cpp_engine_url: "http://localhost:8081"
  video_stream_url: "http://localhost:8082"

log:
  level: "debug"
  format: "text"
  output: "stdout"
  filename: "logs/app.log"
  max_size: 100
  max_age: 7
  max_backups: 10
  compress: true

metrics:
  enabled: true
  path: "/metrics"
  port: 9090